### ISSUE TITLE
ever since v3.0.2 smssync has stopped working

### ISSUE THREAD

**Issue by rm2k** [ushahidi/SMSSync#344]
Ever since I updated to v3.0.2 smssync has stopped working. When I open it I get the following error message `Unfortunately, SMSsync has stopped.` I'm on Android v4.4.2

![img-20151102-wa000](https://cloud.githubusercontent.com/assets/1936364/10892860/5f6cd52e-81ae-11e5-94f5-884149f8ee80.jpg)

**Comment by eyedol** [comment]
This should be fixed in #350 PR

**Comment by rm2k** [comment]
Unfortunately still crashes @ v3.0.3. I don't if I'm doing anything wrong but I've forwarded the crash report.

**Comment by eyedol** [comment]
@rm2k Thanks. Published a buggy APK. Something was broken in our build system. I have republished a new build that should fix it. Let me know how that goes when you get the upgrade. If you can't wait here it's; https://github.com/ushahidi/SMSSync/releases/tag/v3.0.3

**Comment by rm2k** [comment]
ok. its running now. Thanks for the prompt reply.
